# 1. Basic Loop Demonstration

- name: loop demo
  hosts: localhost
  tasks: 
  - name: loop demo
    ansible.builtin.debug:
     msg: "{{ item }}"
    loop:
     - Devops
     - Linux
     - Tarun

# 2. Batch Package Installation

- name: install packages
  hosts: localhost
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: installed
    loop:
     - mysql
     - nginx
     - postfix


  # 3. Managing Package States with Dictionaries
 

- name: manage multiple packages
  hosts: localhost
  become: yes
  tasks:
  - name: manage multiple packages with dict
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: mysql, state: absent }
    - { name: postfix, state: absent }
    - { name: fail2ban, state: installed }




