# 1. Basic Loop Demonstration

- name: loop demo
  hosts: localhost
  tasks: 
  - name: loop demo
    ansible.builtin.debug:
     msg: "{{ item }}"
    loop:
     - Devops
     - Linux
     - Tarun

# 2. Batch Package Installation

- name: loop demo
  hosts: localhost
  tasks: 
  - name: loop demo
    ansible.builtin.dnf:
     msg: "Installation of {{ item }} is success"
     name: "{{ item }}"
     state: installed
    loop:
     - mysql
     - nginx
     - postfix




